### ISSUE TITLE
打印样式不对

### ISSUE THREAD

**Issue by Ritusan** [mycure-inc/vue-html-to-paper#2]
请问打印很多个页面时都每个都要引入css文件吗，这样会不会很繁琐

**Comment by jofftiquez** [comment]
@Ritusan hello! I had to use google translate your issue. However, could you still translate it to English first? Have a good day!

**Comment by jofftiquez** [comment]
@Ritusan also, to answer you question, you only have to inject the css files once, in the initialization part.

**Comment by jofftiquez** [comment]
<img width="660" alt="screen shot 2018-08-24 at 5 44 10 pm" src="https://user-images.githubusercontent.com/8638243/44578178-8cf40b80-a7c5-11e8-9387-83ccbc55b8c4.png">

**Comment by jofftiquez** [comment]
Closing this for now.

**Comment by ensleep** [comment]
Hi,guy. The values disapeared when I print the element witch was render by vue.Does It support to print the page with vue data binding?
