### ISSUE TITLE
Is anyone else getting a "Popups Blocked" error in Chrome?

### ISSUE THREAD

**Issue by tyholby** [mycure-inc/vue-html-to-paper#3]
I click on the demo in the README and it doesn't want to block the print popup. 
But when I use it in my app, it blocks it. Any ideas? See screen shot. 
![image](https://user-images.githubusercontent.com/11578445/45069475-e5f75580-b089-11e8-8d26-bb9a414bc690.png)

**Comment by jofftiquez** [comment]
Hi @tyholby if you look at the [usage](https://github.com/mycure-inc/vue-html-to-paper#usage) part in the documentation, you'll see that you can pass some argument to customize the behaviour or the window.  You can pass `name=_self` to open the print window on the same page. See the set of options [here](https://www.w3schools.com/Jsref/met_win_open.asp).

Kindly close the issue if this helped you. Thanks!
