### ISSUE TITLE
Add body class to use Paper.css

### ISSUE THREAD

**Issue by Tusko** [mycure-inc/vue-html-to-paper#6]
Please add prop to change body class :)
https://github.com/cognitom/paper-css

**Comment by jofftiquez** [comment]
This is nice @Tusko I will consider this. Thanks!

**Comment by jofftiquez** [comment]
Hello @Tusko now that I think about it, you can actually pass the CDN link of paper css to the styles array in the options. 

const options = {
  name: '_blank',
  specs: [
    'fullscreen=yes',
    'titlebar=yes',
    'scrollbars=yes'
  ],
  styles: [
    // Paper css here
  ]
}
