### ISSUE TITLE
Is it possible to be notified when print has been closed?

### ISSUE THREAD

**Issue by MichaelHipp** [mycure-inc/vue-html-to-paper#7]
The call to `this.$htmlToPaper('printMe');` returns immediately, giving no indication that the print screen is still showing nor does it give any indication when it has finished.

Is there a way to get an event or callback or promise when the print window has finished (been closed by the user)?

**Comment by jofftiquez** [comment]
@MichaelHipp I'll see what I can do. Thanks :)

**Comment by Tusko** [comment]
@jofftiquez that's very simple

add after https://github.com/mycure-inc/vue-html-to-paper/blob/267e78b4ff264755bd1172c6657c65a3ee7b8ec7/src/index.js#L51


            this.$emit("printIt", "complete");

**Comment by jofftiquez** [comment]
@Tusko thanks. You can do a PR.

**Comment by jofftiquez** [comment]
@Tusko are you interested to do a PR? If not I will do this. Thanks.

**Comment by Tusko** [comment]
please do it @jofftiquez

**Comment by jofftiquez** [comment]
On it @Tusko

**Comment by jofftiquez** [comment]
Upon checking I can't put an event to this because I am using a mixin and not a component. Maybe a callback will do.

**Comment by jofftiquez** [comment]
Please upgrade to `vue-html-to-paper@1.1.0` and read the docs for callback usage.
