### ISSUE TITLE
How to set Margin and Page breaks

### ISSUE THREAD

**Issue by kmshelke** [mycure-inc/vue-html-to-paper#9]
Hi,

Tanks for wonderful plugin. 

We are using the plugin in a project. We want to know way to set margins and page breaks.
Thanks & Regards,
kmshelke

**Comment by jofftiquez** [comment]
Hello @kmshelke the approach for styling print pages is a little different than a normal page. You should check [this guide](https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/).
